// =============================================
// HYBRIDHIRE AI - Analytics Dashboard
// =============================================

document.addEventListener('DOMContentLoaded', function() {
    
    // ----- UPLOAD RESUMES BUTTON -----
    const uploadBtn = document.getElementById('uploadBtn');
    if (uploadBtn) {
        uploadBtn.addEventListener('click', function() {
            alert('📤 Upload Resumes dialog opened.\n\nSupported formats: PDF, DOCX, TXT');
        });
    }
    
    // ----- DOWNLOAD REPORTS BUTTON -----
const analyticsBtn = document.getElementById("downloadBtn");

if (analyticsBtn) {

    analyticsBtn.addEventListener("click", function () {

        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        doc.setFontSize(20);
        doc.text("HybridHire AI",20,20);

        doc.setFontSize(16);
        doc.text("Recruitment Analytics Report",20,32);

        doc.setFontSize(12);
        doc.text("Generated On: " + new Date().toLocaleDateString(),20,45);

        doc.line(20,50,190,50);

        doc.setFontSize(15);
        doc.text("Overview",20,65);

        doc.setFontSize(11);
        doc.text("Total Resumes : 12,450",25,78);
        doc.text("Shortlisted Candidates : 842",25,88);
        doc.text("Rejected Candidates : 1,230",25,98);
        doc.text("Pending Reviews : 156",25,108);

        doc.setFontSize(15);
        doc.text("Performance Metrics",20,128);

        doc.setFontSize(11);
        doc.text("Hiring Success Rate : 78%",25,140);
        doc.text("AI Matching Accuracy : 92%",25,150);
        doc.text("Average ATS Score : 85%",25,160);
        doc.text("Average Hiring Time : 4 Days",25,170);

        doc.setFontSize(15);
        doc.text("AI Insights",20,190);

        doc.setFontSize(11);
        doc.text("• Backend Developer roles show highest demand.",25,202);
        doc.text("• Java & Spring Boot are top matching skills.",25,212);
        doc.text("• Resume quality improved by 18% this month.",25,222);
        doc.text("• AI recommends reviewing 156 pending resumes.",25,232);

        doc.setFontSize(10);
        doc.text("Generated by HybridHire AI Analytics Dashboard",20,285);

        doc.save("Recruitment_Analytics_Report.pdf");

    });

}
    // ----- LOGOUT BUTTON -----
// ----- LOGOUT -----
const logoutBtn = document.getElementById("logoutBtn");

if (logoutBtn) {

    logoutBtn.addEventListener("click", function (e) {

        e.preventDefault();

        if (confirm("Are you sure you want to logout?")) {

            // Clear login data
            localStorage.removeItem("userRole");
            localStorage.removeItem("userEmail");
            localStorage.removeItem("userName");

            // Optional: clear everything
            // localStorage.clear();

            alert("✅ Logged out successfully!");

            // Redirect to login page
            window.location.href = "login.html";

        }

    });

}
    
    // ----- SEARCH INPUT -----
    // ----- SEARCH ANALYTICS -----
const searchInput = document.getElementById("searchInput");

if (searchInput) {

    searchInput.addEventListener("keypress", function(e) {

        if (e.key === "Enter") {

            const query = this.value.trim().toLowerCase();

            if (query === "") return;

            if (query.includes("resume")) {
                alert("📄 Analytics Found\n\n• Total Resumes : 12,450\n• Resume Growth : +12%");
            }
            else if (query.includes("short")) {
                alert("✅ Shortlisted Candidates\n\n842 Candidates\nGrowth : +5%");
            }
            else if (query.includes("reject")) {
                alert("❌ Rejected Candidates\n\n1,230 Candidates\nTrend : -2%");
            }
            else if (query.includes("pending")) {
                alert("⏳ Pending Reviews\n\n156 Resumes Awaiting Review");
            }
            else if (query.includes("hiring")) {
                alert("📈 Hiring Success Rate\n\n78% Overall Hiring Efficiency");
            }
            else {
                alert("🔍 No matching analytics found.");
            }

        }

    });

}
    
    // ----- TREND SELECT CHANGE -----
    const trendSelect = document.getElementById('trendSelect');
    if (trendSelect) {
        trendSelect.addEventListener('change', function() {
            console.log('📊 Trend period changed to:', this.value);
            // In real implementation, this would reload chart data
        });
    }
    
    // ----- SIMULATED METRIC CARDS ANIMATION (Fade In) -----
    const metricCards = document.querySelectorAll('.grid-cols-1.md\\:grid-cols-2.lg\\:grid-cols-4 .bg-surface-container-lowest');
    metricCards.forEach(function(card, index) {
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        card.style.transition = 'opacity 0.5s ease, transform 0.5s ease';
        
        setTimeout(function() {
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }, 100 + (index * 100));
    });
    
    console.log('✅ HybridHire AI Analytics Dashboard loaded successfully!');
});