// =============================================
// HYBRIDHIRE AI - Student Profile
// =============================================

document.addEventListener('DOMContentLoaded', function() {
    
    // ----- VIEW AI CAREER SCORE -----
    const viewScoreBtn = document.getElementById('viewScoreBtn');
    if (viewScoreBtn) {
        viewScoreBtn.addEventListener('click', function() {
            alert('🧠 AI Career Score: 82/100\n\nBreakdown:\n• ATS Score: 85%\n• AI Match: 92%\n• Job Readiness: 78%\n\nYou are on the right track!');
        });
    }
    
    // ----- EDIT PROFILE (Top Bar) -----
    const editProfileBtn = document.getElementById('editProfileBtn');
    if (editProfileBtn) {
        editProfileBtn.addEventListener('click', function() {
            alert('✏️ Opening profile editor...');
        });
    }
    
    // ----- EDIT PROFILE (Card) -----
    const editProfileBtn2 = document.getElementById('editProfileBtn2');
    if (editProfileBtn2) {
        editProfileBtn2.addEventListener('click', function() {
            alert('✏️ Opening profile editor...');
        });
    }
    
    // ----- APPLY FOR JOBS -----
    const applyJobsBtn = document.getElementById('applyJobsBtn');
    if (applyJobsBtn) {
        applyJobsBtn.addEventListener('click', function() {
            alert('📋 Redirecting to job recommendations...');
            // window.location.href = 'jobs.html';
        });
    }
    
    // ----- DOWNLOAD REPORT -----
const downloadReportBtn = document.getElementById("downloadReportBtn");

if (downloadReportBtn) {
    downloadReportBtn.addEventListener("click", function () {

        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // Title
        doc.setFontSize(20);
        doc.text("HybridHire AI Career Report", 20, 20);

        // Student Details
        doc.setFontSize(14);
        doc.text("Student Profile", 20, 40);

        doc.setFontSize(11);
        doc.text("Name: Alex Chen", 20, 50);
        doc.text("Course: B.S. Computer Science", 20, 58);
        doc.text("University: State University", 20, 66);

        // Scores
        doc.setFontSize(14);
        doc.text("Performance Summary", 20, 85);

        doc.setFontSize(11);
        doc.text("ATS Score : 85%", 25, 95);
        doc.text("AI Match Score : 92%", 25, 103);
        doc.text("Job Readiness : 78%", 25, 111);
        doc.text("Profile Completion : 85%", 25, 119);

        // Strengths
        doc.setFontSize(14);
        doc.text("Strengths", 20, 140);

        doc.setFontSize(11);
        doc.text("• Strong Java & Spring Boot skills", 25, 150);
        doc.text("• Good problem-solving ability", 25, 158);
        doc.text("• Resume is ATS friendly", 25, 166);

        // Recommendations
        doc.setFontSize(14);
        doc.text("AI Recommendations", 20, 185);

        doc.setFontSize(11);
        doc.text("• Add one more full-stack project", 25, 195);
        doc.text("• Improve communication skills", 25, 203);
        doc.text("• Practice mock interviews", 25, 211);
        doc.text("• Complete profile to 100%", 25, 219);

        // Footer
        doc.setFontSize(10);
        doc.text("Generated by HybridHire AI", 20, 285);

        doc.save("Career_Report.pdf");
    });
}
    
    // ----- SIGN OUT -----
    const signOutBtn = document.getElementById('signOutBtn');
    if (signOutBtn) {
        signOutBtn.addEventListener('click', function(e) {
            e.preventDefault();
            if (confirm('Are you sure you want to sign out?')) {
                alert('👋 Signing out...');
                // window.location.href = 'login.html';
            }
        });
    }
    
    console.log('✅ HybridHire AI Student Profile loaded successfully!');
});