// =============================================
// HYBRIDHIRE AI - Resume Analysis
// =============================================

document.addEventListener('DOMContentLoaded', function() {
    
    // ----- EXPORT REPORT -----

const exportBtn = document.getElementById("exportBtn");

if (exportBtn) {
    exportBtn.addEventListener("click", function () {

        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        doc.setFontSize(18);
        doc.text("HybridHire AI Resume Analysis Report", 20, 20);

        doc.setFontSize(12);
        doc.text("Candidate: John Doe", 20, 40);
        doc.text("ATS Score: 87%", 20, 50);
        doc.text("Resume Score: 8.5/10", 20, 60);

        doc.text("Strengths:", 20, 80);
        doc.text("- Strong Java & Spring Boot Skills", 30, 90);
        doc.text("- Good Project Experience", 30, 100);

        doc.text("Suggestions:", 20, 120);
        doc.text("- Add measurable achievements", 30, 130);
        doc.text("- Improve ATS keywords", 30, 140);

        doc.save("Resume_Analysis_Report.pdf");
    });
}
    
    // ----- RE-ANALYZE -----
    const reanalyzeBtn = document.getElementById('reanalyzeBtn');
    if (reanalyzeBtn) {
        reanalyzeBtn.addEventListener('click', function() {
            alert('🔄 Re-analyzing resume...\n\nThis may take a few moments.');
        });
    }
    
    // ----- DOWNLOAD IMPROVED RESUME -----
    // ----- DOWNLOAD IMPROVED RESUME -----
const downloadBtn = document.getElementById("downloadBtn");

if (downloadBtn) {
    downloadBtn.addEventListener("click", function () {

        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // Title
        doc.setFontSize(20);
        doc.text("Improved Resume", 20, 20);

        // Name
        doc.setFontSize(16);
        doc.text("John Doe", 20, 35);

        // Contact
        doc.setFontSize(11);
        doc.text("Email: john.doe@email.com", 20, 45);
        doc.text("Phone: +91-9876543210", 20, 52);

        // Summary
        doc.setFontSize(13);
        doc.text("Professional Summary", 20, 68);

        doc.setFontSize(11);
        doc.text(
            "Java Backend Developer with Spring Boot, REST API,",
            20,
            78
        );
        doc.text(
            "SQL and problem-solving skills. AI optimized for ATS.",
            20,
            85
        );

        // Skills
        doc.setFontSize(13);
        doc.text("Skills", 20, 100);

        doc.setFontSize(11);
        doc.text("• Java", 30, 110);
        doc.text("• Spring Boot", 30, 118);
        doc.text("• REST API", 30, 126);
        doc.text("• SQL", 30, 134);
        doc.text("• Git & GitHub", 30, 142);

        // Education
        doc.setFontSize(13);
        doc.text("Education", 20, 160);

        doc.setFontSize(11);
        doc.text("B.Tech - Computer Science", 30, 170);

        // Footer
        doc.setFontSize(10);
        doc.text(
            "Generated by HybridHire AI - ATS Optimized Resume",
            20,
            285
        );

        doc.save("Improved_Resume.pdf");
    });
}
    
    // ----- ZOOM BUTTONS -----
    const zoomBtns = document.querySelectorAll('.zoom-btn');
    const resumeDocument = document.getElementById('resumeDocument');
    let zoomLevel = 1;
    
    zoomBtns.forEach(function(btn) {
        btn.addEventListener('click', function() {
            const action = this.dataset.zoom;
            if (action === 'in') {
                zoomLevel = Math.min(zoomLevel + 0.1, 2);
            } else {
                zoomLevel = Math.max(zoomLevel - 0.1, 0.5);
            }
            if (resumeDocument) {
                resumeDocument.style.transform = 'scale(' + zoomLevel + ')';
                resumeDocument.style.transformOrigin = 'top left';
            }
        });
    });
    
    // ----- KEYWORD TAGS -----
    const keywordTags = document.querySelectorAll('.keyword-tag');
    keywordTags.forEach(function(tag) {
        tag.addEventListener('click', function() {
            const keyword = this.textContent.trim().replace('+ ', '');
            alert('🔍 Adding keyword: ' + keyword);
        });
    });
    
    // ----- SUGGESTION ITEMS -----
    const suggestionItems = document.querySelectorAll('.suggestion-item');
    suggestionItems.forEach(function(item) {
        item.addEventListener('click', function() {
            const text = this.querySelector('.text-sm')?.textContent || 'Suggestion';
            alert('💡 Applying suggestion:\n\n' + text);
        });
    });
    
    // ----- SIDEBAR NAV ITEMS -----
//     const sidebarLinks = document.querySelectorAll('aside nav a');
//     sidebarLinks.forEach(function(link) {
//         link.addEventListener('click', function(e) {
//             e.preventDefault();
//             const label = this.querySelector('.font-label-md')?.textContent || 'Link';
//             alert('📋 Navigating to: ' + label);
//         });
//     });
    
//     console.log('✅ HybridHire AI Resume Analysis loaded successfully!');
// });

// Analyze Resume Button
const analyzeResumeBtn = document.getElementById("analyzeResumeBtn");

if(analyzeResumeBtn){
    analyzeResumeBtn.addEventListener("click", function(){
        window.location.href = "student-upload.html";
    });
}  
});



